[tool.poetry]
name = "image-filter-pipeline"
version = "0.1.0"
description = ""
authors = ["bikash"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
dask = { extras = ["array", "diagnostics", "dataframe", "delayed", "bag", "pyarrow", "distributed"], version = "2024.8.1" }
ray = { extras = ["default"], version = "2.35.0" }
tqdm = "^4.67.1"
ipywidgets = "^8.1.5"
ultralytics = "^8.3.87"
faiss-cpu = "^1.10.0"
transformers = "^4.49.0"
openai-clip = "^1.0.1"
dask-labextension = "^7.0.0"
torch = "^2.6.0"
notebook = "^7.3.3"
dask-sql = "^2024.5.0"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pre-commit = "^3.8.0"
flake8 = "^7.1.1"
isort = "^5.13.2"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"